### ISSUE TITLE
Can't login to Rdio via Facebook

### ISSUE THREAD

**Issue by Naatan** [tiliado/nuvola-app-rdio#4] opened 2015-08-19 15:06 UTC
It just gives a white loading window that goes on forever. When clicking connect with facebook a popup comes up asking for facebook login information, the popup is horribly styled and doesn't work either.

Using Arch Linux and the latest version from AUR.

Fenryxo's notes:
- System: Arch Linux, not reproducible in Debian Jessie
- Persist with cleared cache/config.
- Epiphany/WebKitGTK MiniBrowser: ?

**Comment by jiri-janousek** [comment] 2015-08-19 15:37
Hello. Thanks for taking the time to report your issue. I need more information to investigate it further:
- Version of Nuvola Player ("the latest version from AUR" is not specific enough)
- Debugging output from terminal during the whole logging in sequence.
- Screenshot of the horribly styled pop-up window.

See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by Naatan** [comment] 2015-08-19 15:52
_Nuvola Player Version_
Nuvola Player 3 Beta 3.0.0
Revision fuzzy

_rdio app version_
nuvola-app-rdio-git  r8.52a785d-1

_Screenshot_
![oqldheytjevl2zadxueyamm8fwgyy9dl3kocqkddfvk](https://cloud.githubusercontent.com/assets/278649/9361249/838be142-4668-11e5-8ece-6879bb3f65ad.png)

_Debug output_

```
[Master:WARNING    Gtk] Theme parsing error: gtk-contained-dark.css:3708:26: negative values are not allowed.
[Master:DEBUG      Gtk] Connecting to session manager
[Master:DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.16.3, CSD on
[Master:DEBUG    Nuvola] config.vala:174: Json Error: Failed to open file '/home/nathan/.config/nuvolaplayer3/master/config.json': No such file or directory
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Test at /usr/share/nuvolaplayer3/web_apps/test, version 1.0
[Master:WARNING  Nuvola] WebAppRegistry.vala:165: Unable to load web app from /usr/share/nuvolaplayer3/web_apps/template: /usr/share/nuvolaplayer3/web_apps/template/metadata.json is not a file
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Google Calendar at /usr/share/nuvolaplayer3/web_apps/google_calendar, version 1.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Rdio at /usr/share/nuvolaplayer3/web_apps/rdio, version 4.0
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Spotify at /usr/share/nuvolaplayer3/web_apps/spotify, version 2.1
[Master:DEBUG    Nuvola] WebAppRegistry.vala:169: Found web app Deezer at /usr/share/nuvolaplayer3/web_apps/deezer, version 2.3
[Master:INFO     Nuvola] WebAppRegistry.vala:89: Using web app Rdio, version 4.0, data dir /usr/share/nuvolaplayer3/web_apps/rdio
[Master:DEBUG    Nuvola] MasterController.vala:380: Launch app runner for 'rdio': /usr/lib/nuvolaplayer3/apprunner -D -a /usr/share/nuvolaplayer3/web_apps/rdio 
[Master:DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
[Runner:WARNING    Gtk] Theme parsing error: gtk-contained-dark.css:3708:26: negative values are not allowed.
[Runner:DEBUG      Gtk] Connecting to session manager
[Runner:DEBUG    DioriteGtk] DesktopShell.vala:90: Shell: gnome shell 3.16.3, CSD on
[Runner:DEBUG    DioriteGtk] application.vala:219: XFCE session vanished: org.xfce.SessionManager
[Master:DEBUG    Nuvola] MasterController.vala:226: Connected to runner server for 'rdio'.
[Runner:WARNING    Gtk] Theme parsing error: gtk-contained-dark.css:3708:26: negative values are not allowed.
[Runner:DEBUG    Nuvola] WebEngine.vala:62: Nuvola WebKit Extension directory: /usr/lib/nuvolaplayer3
[Runner:DEBUG    Nuvola] WebEngine.vala:152: Network Proxy: system settings
[Runner:WARNING  GLib-GObject] g_object_set_property: construct property "local-storage-directory" for object 'WebKitWebContext' can't be set after construction
[Runner:DEBUG    Nuvola] Notifications.vala:175: Notifications: persistence true, actions true, icons false
[Master:DEBUG    Nuvola] MediaKeys.vala:99: GNOME settings daemon appeared: org.gnome.SettingsDaemon, :1.7
[Runner:DEBUG    Nuvola] MPRISProvider.vala:73: Bus acquired: org.mpris.MediaPlayer2.NuvolaPlayer3Rdio, registering objects
[Runner:DEBUG    Nuvola] MPRISProvider.vala:90: Bus name acquired: org.mpris.MediaPlayer2.NuvolaPlayer3Rdio

(WebKitWebProcess:16901): Gtk-WARNING **: Theme parsing error: gtk-contained-dark.css:3708:26: negative values are not allowed.
[Worker:DEBUG    Nuvola] main.vala:232: Page 1 created for (null)
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://www.rdio.com/home/en-us/, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] FormatSupport.vala:88: Trying to play /usr/share/nuvolaplayer3/audio/audiotest.mp3.
[Runner:DEBUG    Nuvola] FormatSupport.vala:88: Pipeline state changed from NULL to READY.
[Runner:DEBUG    Nuvola] FormatSupport.vala:88: Pipeline state changed from READY to PAUSED.
[Runner:DEBUG    Nuvola] FormatSupport.vala:88: Pipeline state changed from PAUSED to PLAYING.
[Runner:DEBUG    Nuvola] FormatSupport.vala:88: End of stream for file /usr/share/nuvolaplayer3/audio/audiotest.mp3.
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Google Talk Plugin (enabled, not flash) at /usr/lib64/mozilla/plugins/libnpgoogletalk.so: Version: 5.41.0.0
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Google Talk Plugin Video Renderer (enabled, not flash) at /usr/lib64/mozilla/plugins/libnpo1d.so: Version: 5.41.0.0
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Gnome Shell Integration (enabled, not flash) at /usr/lib64/mozilla/plugins/libgnome-shell-browser-plugin.so: This plugin provides integration with Gnome Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /usr/lib64/mozilla/plugins/libflashplayer.so: Shockwave Flash 11.2 r202
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Google Talk Plugin (enabled, not flash) at /usr/lib/mozilla/plugins/libnpgoogletalk.so: Version: 5.41.0.0
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Google Talk Plugin Video Renderer (enabled, not flash) at /usr/lib/mozilla/plugins/libnpo1d.so: Version: 5.41.0.0
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Gnome Shell Integration (enabled, not flash) at /usr/lib/mozilla/plugins/libgnome-shell-browser-plugin.so: This plugin provides integration with Gnome Shell for live extension enabling and disabling. It can be used only by extensions.gnome.org
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /usr/lib/mozilla/plugins/libflashplayer.so: Shockwave Flash 11.2 r202
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Google Talk Plugin (enabled, not flash) at /usr/lib/firefox/plugins/libnpgoogletalk.so: Version: 5.41.0.0
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Google Talk Plugin Video Renderer (enabled, not flash) at /usr/lib/firefox/plugins/libnpo1d.so: Version: 5.41.0.0
[Runner:DEBUG    Nuvola] FormatSupportCheck.vala:124: Nuvola.WebPlugin: Shockwave Flash (enabled, flash) at /home/nathan/.mozilla/plugins/libflashplayer.so: Shockwave Flash 11.2 r202
[Runner:WARNING  Nuvola] FormatSupportCheck.vala:137: Too many Flash plugins have been found: 3
http://www.rdio.com/home/en-us/:10:131: CONSOLE ERROR Viewport argument key "target-densitydpi" not recognized and ignored.
[Worker:DEBUG    Nuvola] main.vala:141: Window object cleared: http://www.rdio.com/home/en-us/, 0x2257670, 0x22ecc10, 0x7f246406f4b0
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] WebAppWindow.vala:165: Sidebar position: 837
http://dtp53wusksd88.cloudfront.net/home/static/js/site.min.js?rel=1438035278499559420:3:291: CONSOLE ERROR TypeError: null is not an object (evaluating 'ha')
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-go-next
[Runner:INFO     Nuvola] AppRunnerController.vala:235: Logged in as  ()
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-go-previous
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://static.ak.facebook.com/connect/xd_arbiter/PqAPbTuc2cR.js?version=41#channel=f14a39affc&origin=http%3A%2F%2Fwww.rdio.com, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://s-static.ak.facebook.com/connect/xd_arbiter/PqAPbTuc2cR.js?version=41#channel=f14a39affc&origin=http%3A%2F%2Fwww.rdio.com, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-play
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-pause
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/static/getItem.html?rl_eid=getItem-EQKjPPP&rl_ws=%5B%22rl_campaign%22%5D, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://rlets.com/static/getItem.html?rl_eid=getItem-5q1Xez3&rl_ws=%5B%22RlocalOptOut%22%5D, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/api/v1/insights, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/static/getItem.html?rl_eid=getItem-55su42D&rl_ws=%5B%22visitor_id%22%2C%22visit_id%22%2C%22referrer_type%22%2C%22bot_type%22%2C%22last_activity_at%22%2C%22referrer_url%22%2C%22history_campaign%22%5D, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/static/removeItem.html?rl_eid=removeItem-e6EggUv&rl_ws=%5B%22history_campaign%22%5D, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/api/v1/visits, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/static/setItem.html?rl_eid=setItem-3UUxY07&rl_ws=%5B%7B%22k%22%3A%22visitor_id%22%2C%22v%22%3A%228c1560e5-4946-4751-a4bf-25c2478ed8e2%22%2C%22e%22%3A%22%22%7D%2C%7B%22k%22%3A%22visit_id%22%2C%22v%22%3A%224d711744-2e16-441a-b75f-5135c4011cfd%22%2C%22e%22%3A%22%22%7D%2C%7B%22k%22%3A%22referrer_type%22%2C%22v%22%3A%22DIRECT%22%2C%22e%22%3A%22%22%7D%2C%7B%22k%22%3A%22bot_type%22%2C%22v%22%3A%22%22%2C%22e%22%3A%22%22%7D%2C%7B%22k%22%3A%22last_activity_at%22%2C%22v%22%3A%221439999495234%22%2C%22e%22%3A%22%22%7D%2C%7B%22k%22%3A%22history_campaign%22%2C%22v%22%3A%22%22%2C%22e%22%3A%22%22%7D%2C%7B%22k%22%3A%22referrer_url%22%2C%22v%22%3A%22http%3A%2F%2Fwww.rdio.com%2Fhome%2Fen-us%2F%22%7D%5D, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_OTHER
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/api/v1/insights, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/api/v1/insights, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/api/v1/insights, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://910ec4e2-5138-41e9-9432-9f89d610cefb.rlets.com/api/v1/insights, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = http://www.rdio.com/account/signin/, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_LINK_CLICKED
[Runner:DEBUG    Nuvola] WebEngine.vala:507: Navigation, current window: uri = https://www.rdio.com/account/signin/, result = true, frame = (null), type = WEBKIT_NAVIGATION_TYPE_LINK_CLICKED
[Runner:INFO     Nuvola] config.vala:260: Config saved to /home/nathan/.config/nuvolaplayer3/apps_data/rdio/config.json
[Worker:DEBUG    Nuvola] main.vala:141: Window object cleared: http://www.rdio.com/home/en-us/, 0x2257670, 0x22ecc10, 0x7f246406dcb0
[Worker:DEBUG    Nuvola] jsenvironment.vala:65: ~JsEnvironment 0x22c01b0
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-go-next
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-go-previous
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-play
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: can-pause
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-location
[Runner:DEBUG    Nuvola] DeveloperSidebar.vala:120: Media player notify: artwork-file
```

**Comment by Naatan** [comment] 2015-08-19 15:53
Note that screenshot does not correlate to the debug log. For the debug log I launched nuvolaplayer with rdio and pressed the login button, then all I saw was a white window with a spinner animation. Doesn't seem worthy of a screenshot.

**Comment by jiri-janousek** [comment] 2015-08-20 09:16
Thanks for your response. There is a JavaScript error in the Rdio code that might cause the loading failure. I will investigate it more in [September 2015](https://github.com/tiliado/nuvolaplayer.project/issues/7) as funds for [August 2015](https://github.com/tiliado/nuvolaplayer.project/issues/5) have been exhausted.

`http://dtp53wusksd88.cloudfront.net/home/static/js/site.min.js?rel=1438035278499559420:3:291: CONSOLE ERROR TypeError: null is not an object (evaluating 'ha')`

**Comment by Ch4ni** [comment] 2015-08-20 17:56
I'll start investigating sometime within the next few days. I will post updates here as I come across them.

**Comment by jiri-janousek** [comment] 2015-08-24 09:44
Might be useful for understanding of the error: [Deobfuscated site.min.js](https://gist.github.com/fenryxo/503a11de14d58017bd84#file-site-min-js). I don't have time to identify the line 291 from original source though.

**Comment by jiri-janousek** [comment] 2015-09-13 14:29
Hi @eurythmia, did you have a chance to investigate this issue further?

**Comment by Ch4ni** [comment] 2015-09-13 16:14
sorry, no. I've hardly had a chance to sit in front of my computer in the
past few weeks.

**Comment by jiri-janousek** [comment] 2015-09-27 12:10
I'm assigning this issue to me and will take a look at it in October 2015.

**Comment by Naatan** [comment] 2015-10-08 15:19
Glad you're on top of it. Is there any workaround that I could try for the time being? Would love to be able to us this :)

**Comment by jiri-janousek** [comment] 2015-10-09 22:28
I'm afraid I cannot reproduce the issue. Could you try to remove Rdio configuration and cache?

```
rm -rf ~/.config/nuvolaplayer3/apps_data/rdio
rm -rf ~/.cache/nuvolaplayer3/apps_data/rdio
rm -r ~/.local/share/nuvolaplayer3/apps_data/rdio
```

**Comment by Naatan** [comment] 2015-10-09 22:31
No dice. I am using gnome-shell, in case that matters ..

**Comment by jiri-janousek** [comment] 2015-10-10 09:23
Does the issue occur also in GNOME Web/Epiphany browser?

**Closed as completed** 2022-05-03 08:16 UTC
Labels: bug, more information required
